version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  WEBHOOK_URL:
    secure: iGW1I2Gs3o0hzHyPPRhbvnbfhMY1qIjcCMVUeBguWgCF3g7jAmIRdG9vVJwoTpVoqsUAQEwofUt9C2MaU5GQZNuj7fuvd6EbcR3hHnU3WqWYapAvjelQy2Rp3b5qBhSPlMz42q68f7jTNWfTWQnMeVbRfegvmEGAmXi65OsvAP4=
build:
  publish_core_console: true
  verbosity: minimal
