version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  WEBHOOK_URL:
    secure: iGW1I2Gs3o0hzHyPPRhbvnbfhMY1qIjcCMVUeBguWgCF3g7jAmIRdG9vVJwoTpVoqsUAQEwofUt9C2MaU5GQZNuj7fuvd6EbcR3hHnU3WqWYapAvjelQy2Rp3b5qBhSPlMz42q68f7jTNWfTWQnMeVbRfegvmEGAmXi65OsvAP4=
build:
  publish_core_console: true
  verbosity: minimal
 on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
