version: 1.0.{build}
before_build:
  - nuget restore
pull_requests:
  do_not_increment_build_number: true
environment:
  WEBHOOK_URL:
    secure: iGW1I2Gs3o0hzHyPPRhbvnbfhMY1qIjcCMVUeBguWgCF3g7jAmIRdG9vVJwoTpVoqsUAQEwofUt9C2MaU5GQZNuj7fuvd6EbcR3hHnU3WqWYapAvjelQy2Rp3b5qBhSPlMz42q68f7jTNWfTWQnMeVbRfegvmEGAmXi65OsvAP4=
build:
  publish_core_console: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/487416853040463883/OvjSYMQsTvmhiumqFX4eIVXCoVoAexOGnut_sZBIdQHMOUVOS2EHqW0iMAidC2wr09hb
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
